// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LAPhil.iOS
{
	public partial class WebStoreView : UIViewController
	{
		public WebStoreView (IntPtr handle) : base (handle)
		{
		}
	}
}
