// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HollywoodBowl.iOS
{
	public partial class ChooseEventTypeTableViewController : UITableViewController
	{
		public ChooseEventTypeTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
