// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HollywoodBowl.iOS
{
	public partial class tabBarRootViewController : UITabBarController
	{
		public tabBarRootViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
