#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MonoDroid.TimesSquare.Resource", IsApplication=false)]

namespace MonoDroid.TimesSquare
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int dayBackground = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int dayTextColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int dividerColor = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int headerTextColor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int state_current_month = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public static int state_highlighted = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int state_range_first = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public static int state_range_last = 2130771978;
			
			// aapt resource value: 0x7f010009
			public static int state_range_middle = 2130771977;
			
			// aapt resource value: 0x7f010005
			public static int state_selectable = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int state_today = 2130771975;
			
			// aapt resource value: 0x7f010003
			public static int titleTextColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public static int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public static int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public static int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public static int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public static int calendar_text_selector = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public static int calendar_text_unselectable = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int calendar_text_small = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int calendar_text_title = 2131034117;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int calendar_bg_selector = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public static int calendar_grid = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int title = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int month = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int week = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public static int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public static int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public static int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public static int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public static int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public static int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CalendarPickerView = new int[] {
					16842964,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public static int CalendarPickerView_android_background = 0;
			
			// aapt resource value: 2
			public static int CalendarPickerView_dayBackground = 2;
			
			// aapt resource value: 3
			public static int CalendarPickerView_dayTextColor = 3;
			
			// aapt resource value: 1
			public static int CalendarPickerView_dividerColor = 1;
			
			// aapt resource value: 5
			public static int CalendarPickerView_headerTextColor = 5;
			
			// aapt resource value: 4
			public static int CalendarPickerView_titleTextColor = 4;
			
			public static int[] calendar_cell = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public static int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public static int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public static int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public static int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public static int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public static int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public static int calendar_cell_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
